snoop:
   applicationName: snoopworld
   applicationHome: http://localhost:8080/snoop-world-service/
   applicationServiceRoot: api
#   serviceHost: localhost:8080/snoop-service/
   serviceHost: 192.168.59.103:8081/snoop-service/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  